
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author frimp
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
 
    public IssueBook() {
        initComponents();
          
    }
         
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StudentIdTextField = new javax.swing.JTextField();
        BookIDTextField = new javax.swing.JTextField();
        IssueBookButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IssueBookTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 102, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("BOOK ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 80, -1));

        StudentIdTextField.setBackground(new java.awt.Color(255, 255, 204));
        StudentIdTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(StudentIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 320, 30));

        BookIDTextField.setBackground(new java.awt.Color(255, 255, 204));
        BookIDTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BookIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(BookIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 140, 320, 30));

        IssueBookButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IssueBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/issue book.png"))); // NOI18N
        IssueBookButton.setText("ISSUE BOOK");
        IssueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IssueBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 180, 40));

        IssueBookTextArea.setEditable(false);
        IssueBookTextArea.setBackground(new java.awt.Color(255, 255, 204));
        IssueBookTextArea.setColumns(20);
        IssueBookTextArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IssueBookTextArea.setRows(5);
        jScrollPane1.setViewportView(IssueBookTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 400, 140));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/123456.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIDTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IssueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookButtonActionPerformed
       if(StudentIdTextField.getText().equals("221030190") && BookIDTextField.getText().equals("001"))
       {
       
           IssueBookTextArea.setText("*** DATABASE UPDATED ***"+ "\n"+"BOOK ISSUED TO: Mohammed Hussein"+ "\n"+"BOOK TITLE: LAW OF GHANA"
           + "\n"+"DATE OF RETURN:18 MAY 2023"+ "\n"+"BOOK CONDITION: NEW");
               
       }else
       {
           JOptionPane.showMessageDialog(null, "INVALID STUDENT ID OR BOOK TILE");
       }
    }//GEN-LAST:event_IssueBookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BookIDTextField;
    private javax.swing.JButton IssueBookButton;
    private javax.swing.JTextArea IssueBookTextArea;
    private javax.swing.JTextField StudentIdTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
