
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author frimp
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */
    DefaultTableModel model;
    public NewStudent() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GENDERBUTTON = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        REGNAME = new javax.swing.JTextField();
        LNAMEFIELD = new javax.swing.JTextField();
        EMAILFIELD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CourseComboBox = new javax.swing.JComboBox<>();
        SAVESTUDENTBUTTON = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        REGTABLE = new javax.swing.JTable();
        FreeBooksTextArea = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        STUDENTIDFIL1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FreeBooksTextArea1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NAME:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("LAST NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("GENDER:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("STUDENT ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        buttonGroup1.add(GENDERBUTTON);
        GENDERBUTTON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GENDERBUTTON.setText("Male");
        getContentPane().add(GENDERBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 68, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 81, -1));

        REGNAME.setBackground(new java.awt.Color(255, 255, 204));
        REGNAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(REGNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 290, -1));

        LNAMEFIELD.setBackground(new java.awt.Color(255, 255, 204));
        LNAMEFIELD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(LNAMEFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 290, -1));

        EMAILFIELD.setBackground(new java.awt.Color(255, 255, 204));
        EMAILFIELD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(EMAILFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("INTEREST:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sports", "Biography", "Science", "Novels" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 245, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("COURSE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 85, -1));

        CourseComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Business", "Law", "Economics", " " }));
        CourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CourseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 240, 30));

        SAVESTUDENTBUTTON.setBackground(new java.awt.Color(255, 255, 204));
        SAVESTUDENTBUTTON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SAVESTUDENTBUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/save-icon--1.png"))); // NOI18N
        SAVESTUDENTBUTTON.setText("SAVE");
        SAVESTUDENTBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVESTUDENTBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(SAVESTUDENTBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 160, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Free Book:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        REGTABLE.setBackground(new java.awt.Color(255, 255, 204));
        REGTABLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        REGTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "NAME", "LAST NAME", "GENDER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(REGTABLE);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 820, 150));

        FreeBooksTextArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(FreeBooksTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 290, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("EMAIL:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        STUDENTIDFIL1.setBackground(new java.awt.Color(255, 255, 204));
        STUDENTIDFIL1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(STUDENTIDFIL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 290, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/123456.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 630, 440));

        FreeBooksTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(FreeBooksTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 290, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/123456.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 480, 450));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/123456.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 384, 670, 210));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/123456.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 210, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SAVESTUDENTBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVESTUDENTBUTTONActionPerformed
        // TODO add your handling code here:
       if(STUDENTIDFIL1.getText().equals("")||REGNAME.getText().equals("")||LNAMEFIELD.getText().equals(""))
       {
           JOptionPane.showMessageDialog(this, "Enter All Data");
       }
       else
       {
           String [] data={STUDENTIDFIL1.getText(),REGNAME.getText(),LNAMEFIELD.getText(),GENDERBUTTON.getText()};
           DefaultTableModel tblmodel=(DefaultTableModel)REGTABLE.getModel();
           tblmodel.addRow(data);
           
           JOptionPane.showMessageDialog(this, "Data Saved Successfully");
           
           STUDENTIDFIL1.setText("");
           REGNAME.setText("");
           LNAMEFIELD.setText("");
           EMAILFIELD.setText("");
           
           
           
       }
        
        
    }//GEN-LAST:event_SAVESTUDENTBUTTONActionPerformed

    private void CourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboBoxActionPerformed
        // TODO add your handling code here:
        String comp="Calculus 1";
        String law="Law of Ghana";
        String business="Bill Gate and the World";
        String Economics="Power of Tax";
        if(CourseComboBox.getSelectedItem().equals("Computer Science"))
        {
            FreeBooksTextArea.setText(comp);
        }else if(CourseComboBox.getSelectedItem().equals("Law"))
        {
            FreeBooksTextArea.setText(law);
        }else if(CourseComboBox.getSelectedItem().equals("Business"))
        {
            FreeBooksTextArea.setText(business);
        }else if(CourseComboBox.getSelectedItem().equals("Economics"))
        {
            FreeBooksTextArea.setText(Economics);
        }
    }//GEN-LAST:event_CourseComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CourseComboBox;
    private javax.swing.JTextField EMAILFIELD;
    private javax.swing.JLabel FreeBooksTextArea;
    private javax.swing.JLabel FreeBooksTextArea1;
    private javax.swing.JRadioButton GENDERBUTTON;
    private javax.swing.JTextField LNAMEFIELD;
    private javax.swing.JTextField REGNAME;
    private javax.swing.JTable REGTABLE;
    private javax.swing.JButton SAVESTUDENTBUTTON;
    private javax.swing.JTextField STUDENTIDFIL1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
