
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author frimp
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReturnBookButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        STUDIDFIELD = new javax.swing.JTextField();
        BOKIDFIELD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        J2Slider = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReturnField = new javax.swing.JTextArea();
        J2SliderLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 94, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("BOOK ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        ReturnBookButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ReturnBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/return book png.png"))); // NOI18N
        ReturnBookButton.setText("RETURN BOOK");
        ReturnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 180, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 180, 40));

        STUDIDFIELD.setBackground(new java.awt.Color(255, 255, 204));
        STUDIDFIELD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(STUDIDFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 91, 380, 30));

        BOKIDFIELD.setBackground(new java.awt.Color(255, 255, 204));
        BOKIDFIELD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(BOKIDFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 141, 380, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("BOOK CONDITION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 224, 149, -1));

        J2Slider.setBackground(new java.awt.Color(255, 255, 204));
        J2Slider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        J2Slider.setMajorTickSpacing(1);
        J2Slider.setMaximum(3);
        J2Slider.setMinimum(1);
        J2Slider.setPaintLabels(true);
        J2Slider.setPaintTicks(true);
        J2Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                J2SliderStateChanged(evt);
            }
        });
        getContentPane().add(J2Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 206, 380, -1));

        ReturnField.setBackground(new java.awt.Color(255, 255, 204));
        ReturnField.setColumns(20);
        ReturnField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ReturnField.setRows(5);
        jScrollPane2.setViewportView(ReturnField);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 400, 100));

        J2SliderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(J2SliderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 370, 21));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulibrary/123456.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ReturnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "System Updated Succesfully");
         if(STUDIDFIELD.getText().equals("221030190") && BOKIDFIELD.getText().equals("001"))
       {
       
           ReturnField.setText("*** DATABASE UPDATED ***"+ "\n"+"BOOK RETURNED BY: MURPHY KWAME"+ "\n"+"BOOK TITLE: LAW OF GHANA"
           + "\n"+"DATE OF RETURN:18 May 2023");
               
       }else
       {
           JOptionPane.showMessageDialog(null, "INVALID STUDENT ID OR BOOK TILE");
       }
    }//GEN-LAST:event_ReturnBookButtonActionPerformed

    private void J2SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_J2SliderStateChanged
         if(J2Slider.getValue()==1)
        {
            J2SliderLabel.setText("BOOK IN VERY BAD CONDITION");
        }else if(J2Slider.getValue()==2)
        {
            J2SliderLabel.setText("BOOK IS IN NORMAL CONDITION");
        }else if(J2Slider.getValue()==3)
        {
            J2SliderLabel.setText("BOOK IS NEW");
        }
    }//GEN-LAST:event_J2SliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BOKIDFIELD;
    private javax.swing.JSlider J2Slider;
    private javax.swing.JLabel J2SliderLabel;
    private javax.swing.JButton ReturnBookButton;
    private javax.swing.JTextArea ReturnField;
    private javax.swing.JTextField STUDIDFIELD;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
